### ISSUE TITLE
Why Confusion Matrix showing background FN and background FP?

### ISSUE THREAD

**Issue by prasaddev97** [rohan1198/YOLOv5-end-to-end#1]
When ever  I am running the code Yolov5Augmentationtraining.ipynb, confusion matrix is showing background FN and background FP. But number of classes is 12. It should be 12 by 12 cell in confusion matrix.. Can you explain me?

**Comment by rohan1198** [comment]
Background FN/FP is usually for empty classes. i.e. images with no corresponding annotations. My dataset had a few images with no annotations (because there were no chess pieces in those images), so you can see that column in the confusion matrix. Hope I have cleared your doubt.
